-- CONNECT SYS
ALTER SESSION SET EVENTS '10150 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '10904 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '25475 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '10407 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '10851 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '22830 TRACE NAME CONTEXT FOREVER, LEVEL 192 ';
-- new object type path: DATABASE_EXPORT/SCHEMA/USER
 CREATE USER "ZHAQUSER" IDENTIFIED BY VALUES 'S:C98E539EABD61EA196AE48CD960F2DE392C6F7FC3C4FBFCA52E10760B0A5;T:C419EC62CC5A80A0B4BC178231DA27E2F42147772E031EF4E0612D84D97F92B5EBB856EA70DC071B7BFCF168BED1A61921F0B49B2B884E4B0913D8386F4058A7A485CE2DA53E1CE29817F21ECEF0A244;D961D7BA671409BD'
      DEFAULT TABLESPACE "ZHAQ"
      TEMPORARY TABLESPACE "TEMP";
-- new object type path: DATABASE_EXPORT/SCHEMA/GRANT/SYSTEM_GRANT
GRANT CREATE SESSION TO "ZHAQUSER";
GRANT CREATE TABLE TO "ZHAQUSER";
GRANT CREATE VIEW TO "ZHAQUSER";
GRANT UNLIMITED TABLESPACE TO "ZHAQUSER" WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO "ZHAQUSER";
-- new object type path: DATABASE_EXPORT/SCHEMA/ROLE_GRANT
 GRANT "CONNECT" TO "ZHAQUSER";
 GRANT "RESOURCE" TO "ZHAQUSER";
-- new object type path: DATABASE_EXPORT/SCHEMA/DEFAULT_ROLE
 ALTER USER "ZHAQUSER" DEFAULT ROLE ALL;
-- new object type path: DATABASE_EXPORT/SCHEMA/TABLESPACE_QUOTA
-- CONNECT SYSTEM
DECLARE 
  TEMP_COUNT NUMBER; 
  SQLSTR VARCHAR2(200); 
BEGIN 
  SQLSTR := 'ALTER USER "ZHAQUSER" QUOTA UNLIMITED ON "ZHAQ"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION 
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN 
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES 
              WHERE TABLESPACE_NAME = ''ZHAQ'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN; 
      ELSE RAISE; 
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/
-- new object type path: DATABASE_EXPORT/SCHEMA/SEQUENCE/SEQUENCE
-- CONNECT SYS
 CREATE SEQUENCE  "ZHAQUSER"."SEQ_SYS_CAR_INFO_STR_CARSNO"  MINVALUE 1 MAXVALUE 9999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
-- new object type path: DATABASE_EXPORT/SCHEMA/PROCACT_SCHEMA
-- CONNECT ZHAQUSER

BEGIN 
sys.dbms_logrep_imp.instantiate_schema(schema_name=>SYS_CONTEXT('USERENV','CURRENT_SCHEMA'), export_db_name=>'ZHAQ', inst_scn=>'110294414');
COMMIT; 
END; 
/ 
-- new object type path: DATABASE_EXPORT/SCHEMA/TABLE/TABLE
-- CONNECT SYS
CREATE TABLE "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD" 
   (	"PLAN_TASK_ID" VARCHAR2(40 BYTE), 
	"BRANCH_ID" VARCHAR2(40 BYTE), 
	"BRANCH_NAME" VARCHAR2(40 BYTE), 
	"INSPECT_NAME" VARCHAR2(40 BYTE), 
	"STAFF_NO" VARCHAR2(40 BYTE), 
	"STAFF_NAME" VARCHAR2(40 BYTE), 
	"INSPECTOR_TYPE" VARCHAR2(40 BYTE), 
	"INSPECT_CONTENT" VARCHAR2(2000 BYTE), 
	"INSPECTION_STANDARD" VARCHAR2(2000 BYTE), 
	"CONFIG_SOURCE" NVARCHAR2(20), 
	"FILL_RESULT" NVARCHAR2(20), 
	"RECORD_STATUS" VARCHAR2(40 BYTE), 
	"CHECK_SUMMARY" VARCHAR2(40 BYTE), 
	"CHECK_NUM" VARCHAR2(40 BYTE), 
	"DANGER_TYPE" VARCHAR2(40 BYTE), 
	"PROBLEM_REMARK" VARCHAR2(400 BYTE), 
	"ISSUE_IMAGE" VARCHAR2(400 BYTE), 
	"RECTIFICATION_STATUS" NVARCHAR2(20), 
	"RECTIFICATION_ID" VARCHAR2(40 BYTE), 
	"DANGER_GRADE" NVARCHAR2(20), 
	"ID" NVARCHAR2(40) NOT NULL ENABLE, 
	"CREATE_USER_NO" NVARCHAR2(40) NOT NULL ENABLE, 
	"CREATE_DATE_TIME" NVARCHAR2(20) NOT NULL ENABLE, 
	"UPDATE_USER_NO" NVARCHAR2(40), 
	"UPDATE_DATE_TIME" NVARCHAR2(20), 
	"COMPANY_ID" NVARCHAR2(100), 
	"COLLECT_STAFF" VARCHAR2(40 BYTE), 
	"INSPECT_ID" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZHAQ" ;
CREATE TABLE "ZHAQUSER"."ACT_RE_CAMFORMDEF" 
   (	"ID_" NVARCHAR2(64), 
	"REV_" NUMBER(38,0), 
	"KEY_" NVARCHAR2(255), 
	"VERSION_" NUMBER(38,0), 
	"DEPLOYMENT_ID_" NVARCHAR2(64), 
	"RESOURCE_NAME_" NVARCHAR2(2000), 
	"TENANT_ID_" NVARCHAR2(64)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "ZHAQ" ;
-- new object type path: DATABASE_EXPORT/SCHEMA/TABLE/COMMENT
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."PLAN_TASK_ID" IS '计划任务ID';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."BRANCH_ID" IS '部门ID';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."BRANCH_NAME" IS '部门名称';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."INSPECT_NAME" IS '安全检查名称';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."STAFF_NO" IS '检查人工号';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."STAFF_NAME" IS '检查人姓名';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."INSPECTOR_TYPE" IS '检查人员类型';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."INSPECT_CONTENT" IS '检查项目';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."INSPECTION_STANDARD" IS '检查标准';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."CONFIG_SOURCE" IS '来源1.PC端2.移动端';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."FILL_RESULT" IS '结果1.正常0.异常';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."RECORD_STATUS" IS '检查状态：默认0，生成记录为1';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."CHECK_SUMMARY" IS '是否汇总1.汇总2.不汇总';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."CHECK_NUM" IS '检查数量';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."DANGER_TYPE" IS '隐患类别';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."PROBLEM_REMARK" IS '问题描述';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."ISSUE_IMAGE" IS '问题图片id,逗号相隔';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."RECTIFICATION_STATUS" IS '隐患整改状态';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."RECTIFICATION_ID" IS '隐患整改ID';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."DANGER_GRADE" IS '隐患等级';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."ID" IS '主键ID:主键ID';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."CREATE_USER_NO" IS '创建人:创建人';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."CREATE_DATE_TIME" IS '创建时间:创建时间';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."UPDATE_USER_NO" IS '更新人:更新人';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."UPDATE_DATE_TIME" IS '更新时间:更新时间';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."COMPANY_ID" IS '公司别:公司别';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."COLLECT_STAFF" IS '汇总的人员';
 COMMENT ON COLUMN "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"."INSPECT_ID" IS '检查项id';
 COMMENT ON TABLE "ZHAQUSER"."HT_PLAN_INSPECTION_MANAGE_CHECKER_RECORD"  IS '计划性检查检查人员填报记录表';
ALTER TABLE "ZHAQUSER"."PER_PERSONNEL_T_A_RECORD_DETAIL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZHAQ"  ENABLE;
ALTER TABLE "ZHAQUSER"."FC_MAJOR_HAZARD_ALARM_CHAIN_ARRANGEMENT" ADD CONSTRAINT "SYS_C0038950" CHECK ("ID" IS NOT NULL) ENABLE;
ALTER TABLE "ZHAQUSER"."FC_MAJOR_HAZARD_ALARM_CHAIN_ARRANGEMENT" ADD CONSTRAINT "FC_MAJOR_HAZARD_ALARM_CHAIN_ARRANGEMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ZHAQ"  ENABLE;
-- new object type path: DATABASE_EXPORT/SCHEMA/TABLE/INDEX/STATISTICS/INDEX_STATISTICS
-- new object type path: DATABASE_EXPORT/SCHEMA/TABLE/STATISTICS/TABLE_STATISTICS
-- new object type path: DATABASE_EXPORT/STATISTICS/MARKER
-- fixup virtual columns... 
-- done fixup virtual columns 
