/*
 Navicat Premium Data Transfer

 Source Server         : NG_SBZW_测
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Host           : 172.18.247.107:1521
 Source Schema         : ZHYWUSER

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 04/09/2025 19:13:07
*/


-- ----------------------------
-- Table structure for MH_CW_RECORD
-- ----------------------------
DROP TABLE "ZHYWUSER"."MH_CW_RECORD";
CREATE TABLE "ZHYWUSER"."MH_CW_RECORD" (
  "ID" VARCHAR2(64 BYTE) VISIBLE NOT NULL,
  "CREATE_USER_NO" VARCHAR2(64 BYTE) VISIBLE,
  "CREATE_DATE_TIME" VARCHAR2(30 BYTE) VISIBLE,
  "UPDATE_USER_NO" VARCHAR2(64 BYTE) VISIBLE,
  "UPDATE_DATE_TIME" VARCHAR2(30 BYTE) VISIBLE,
  "COMPANY_ID" VARCHAR2(64 BYTE) VISIBLE,
  "I_LEVEL" VARCHAR2(30 BYTE) VISIBLE,
  "STATUS" NUMBER(1,0) VISIBLE DEFAULT 1,
  "COM_CODE" VARCHAR2(255 BYTE) VISIBLE,
  "APPLY_NO" VARCHAR2(255 BYTE) VISIBLE,
  "APPLY_PERSON" VARCHAR2(255 BYTE) VISIBLE,
  "USE_DEPT" VARCHAR2(255 BYTE) VISIBLE,
  "PURPOSE" VARCHAR2(255 BYTE) VISIBLE,
  "WAREHOUSE" VARCHAR2(255 BYTE) VISIBLE,
  "JZ_NO" VARCHAR2(255 BYTE) VISIBLE,
  "GCLX_NO" VARCHAR2(255 BYTE) VISIBLE,
  "GCHY_NO" VARCHAR2(255 BYTE) VISIBLE,
  "KS_NO" VARCHAR2(255 BYTE) VISIBLE,
  "MATERIAL_NO" VARCHAR2(255 BYTE) VISIBLE,
  "MATERIAL_NAME" VARCHAR2(255 BYTE) VISIBLE,
  "QUANTITY" VARCHAR2(255 BYTE) VISIBLE,
  "UNIT" VARCHAR2(255 BYTE) VISIBLE,
  "PRICE" VARCHAR2(255 BYTE) VISIBLE,
  "AMOUNT" VARCHAR2(255 BYTE) VISIBLE,
  "STORAGE" VARCHAR2(255 BYTE) VISIBLE,
  "SUPPLIER_NO" VARCHAR2(255 BYTE) VISIBLE,
  "SUPPLIER_NAME" VARCHAR2(255 BYTE) VISIBLE,
  "SHORT_NAME" VARCHAR2(255 BYTE) VISIBLE,
  "REMARK" VARCHAR2(255 BYTE) VISIBLE,
  "BATCH_NO" VARCHAR2(255 BYTE) VISIBLE,
  "TYPE" VARCHAR2(255 BYTE) VISIBLE,
  "IN_STORAGE" VARCHAR2(255 BYTE) VISIBLE,
  "SPARE_LOG" VARCHAR2(255 BYTE) VISIBLE,
  "QR_CODE_TEMPLATE" VARCHAR2(2000 BYTE) VISIBLE,
  "QR_CODE_NODE_LIST" VARCHAR2(2000 BYTE) VISIBLE,
  "SIDE_ID" VARCHAR2(64 BYTE) VISIBLE,
  "STORAGE_ID" VARCHAR2(64 BYTE) VISIBLE,
  "IN_LX" VARCHAR2(2 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."ID" IS '主键ID';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."CREATE_USER_NO" IS '创建人';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."CREATE_DATE_TIME" IS '创建时间';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."UPDATE_USER_NO" IS '修改人';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."UPDATE_DATE_TIME" IS '修改时间';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."COMPANY_ID" IS '公司ID';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."I_LEVEL" IS '优先级';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."STATUS" IS '状态  1可用，0不可用';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."COM_CODE" IS '公司别';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."APPLY_NO" IS '申请单号';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."APPLY_PERSON" IS '申请人';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."USE_DEPT" IS '用料单位';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."PURPOSE" IS '用途别';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."WAREHOUSE" IS '发料仓库';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."JZ_NO" IS '记账编号';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."GCLX_NO" IS '工程立项号';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."GCHY_NO" IS '工程合约号';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."KS_NO" IS '客商编号';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."MATERIAL_NO" IS '料号';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."MATERIAL_NAME" IS '物料名称';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."QUANTITY" IS '数量';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."UNIT" IS '计量单位';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."PRICE" IS '单价';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."AMOUNT" IS '金额';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."STORAGE" IS '储位';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."SUPPLIER_NO" IS '供应商编号';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."SUPPLIER_NAME" IS '供应商名称';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."SHORT_NAME" IS '供应商简称';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."REMARK" IS '备注';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."BATCH_NO" IS '批号';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."TYPE" IS '类型';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."IN_STORAGE" IS '是否已入库  Y-是; N-否';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."SPARE_LOG" IS '备件标识';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."QR_CODE_TEMPLATE" IS '二维码模板信息';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."QR_CODE_NODE_LIST" IS '二维码erp各节点信息';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."SIDE_ID" IS '库位id';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."STORAGE_ID" IS '储位id';
COMMENT ON COLUMN "ZHYWUSER"."MH_CW_RECORD"."IN_LX" IS '入特钢离线：Y=是';
COMMENT ON TABLE "ZHYWUSER"."MH_CW_RECORD" IS '备材需求申报明细表';

-- ----------------------------
-- Primary Key structure for table MH_CW_RECORD
-- ----------------------------
ALTER TABLE "ZHYWUSER"."MH_CW_RECORD" ADD CONSTRAINT "SYS_C0014144" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table MH_CW_RECORD
-- ----------------------------
ALTER TABLE "ZHYWUSER"."MH_CW_RECORD" ADD CONSTRAINT "SYS_C0010001" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZHYWUSER"."MH_CW_RECORD" ADD CONSTRAINT "SYS_C0040294" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
