/*
 Navicat Premium Data Transfer

 Source Server         : NG_SBZW_测
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Host           : 172.18.247.107:1521
 Source Schema         : ZHYWUSER

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 04/09/2025 19:12:46
*/


-- ----------------------------
-- Table structure for MH_SIDE_STOCK
-- ----------------------------
DROP TABLE "ZHYWUSER"."MH_SIDE_STOCK";
CREATE TABLE "ZHYWUSER"."MH_SIDE_STOCK" (
  "ID" VARCHAR2(32 BYTE) VISIBLE NOT NULL,
  "MATERIAL_NO" VARCHAR2(32 BYTE) VISIBLE,
  "STORAGE_ID" VARCHAR2(32 BYTE) VISIBLE,
  "BATCH_NO" VARCHAR2(30 BYTE) VISIBLE,
  "MATERIAL_TYPE" VARCHAR2(30 BYTE) VISIBLE,
  "QUANTITY" NUMBER(20,0) VISIBLE,
  "UNIT" VARCHAR2(30 BYTE) VISIBLE,
  "AMOUNT" NUMBER(20,3) VISIBLE,
  "STOCK_TYPE" VARCHAR2(30 BYTE) VISIBLE,
  "REMARK" VARCHAR2(100 BYTE) VISIBLE,
  "CREATE_USER_NO" VARCHAR2(64 BYTE) VISIBLE,
  "CREATE_DATE_TIME" VARCHAR2(30 BYTE) VISIBLE,
  "UPDATE_USER_NO" VARCHAR2(64 BYTE) VISIBLE,
  "UPDATE_DATE_TIME" VARCHAR2(30 BYTE) VISIBLE,
  "COMPANY_ID" VARCHAR2(64 BYTE) VISIBLE,
  "I_LEVEL" VARCHAR2(30 BYTE) VISIBLE,
  "STATUS" NUMBER(1,0) VISIBLE DEFAULT 1,
  "CREATE_USER_DEPT" VARCHAR2(255 BYTE) VISIBLE,
  "CREATE_USER_FACTORY" VARCHAR2(255 BYTE) VISIBLE,
  "MATERIAL_NAME" VARCHAR2(255 BYTE) VISIBLE,
  "MODEL" VARCHAR2(255 BYTE) VISIBLE,
  "SPARE_LOG" VARCHAR2(255 BYTE) VISIBLE,
  "RELATE_ORDER_NO" VARCHAR2(64 BYTE) VISIBLE,
  "RELATE_REPAIR_ID" VARCHAR2(64 BYTE) VISIBLE,
  "SUPPLIER" VARCHAR2(100 BYTE) VISIBLE,
  "DEVICE_ID" VARCHAR2(64 BYTE) VISIBLE,
  "FACTORY" VARCHAR2(64 BYTE) VISIBLE,
  "OFFLINE_POSITION" VARCHAR2(64 BYTE) VISIBLE,
  "OFFLINE_TIME" VARCHAR2(30 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."ID" IS '主键ID';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."MATERIAL_NO" IS '料号';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."STORAGE_ID" IS '储位ID';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."BATCH_NO" IS '批号';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."MATERIAL_TYPE" IS '物料类型';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."QUANTITY" IS '数量';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."UNIT" IS '计量单位';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."AMOUNT" IS '总价';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."STOCK_TYPE" IS '库存类型';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."REMARK" IS '备注';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."CREATE_USER_NO" IS '创建人';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."CREATE_DATE_TIME" IS '创建时间';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."UPDATE_USER_NO" IS '修改人';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."UPDATE_DATE_TIME" IS '修改时间';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."COMPANY_ID" IS '公司ID';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."I_LEVEL" IS '优先级';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."STATUS" IS '状态  0可用，1不可用';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."CREATE_USER_DEPT" IS '创建者部门';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."CREATE_USER_FACTORY" IS '创建者生产厂';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."MATERIAL_NAME" IS '物料名称';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."MODEL" IS '型号规格';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."SPARE_LOG" IS '备件标识';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."RELATE_ORDER_NO" IS '关联总库领料单号';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."RELATE_REPAIR_ID" IS '关联备件修理申报id';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."SUPPLIER" IS '厂商';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."DEVICE_ID" IS '所属设备';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."FACTORY" IS '生产厂';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."OFFLINE_POSITION" IS '下线位置';
COMMENT ON COLUMN "ZHYWUSER"."MH_SIDE_STOCK"."OFFLINE_TIME" IS '下线时间';
COMMENT ON TABLE "ZHYWUSER"."MH_SIDE_STOCK" IS '机旁库库存表';

-- ----------------------------
-- Checks structure for table MH_SIDE_STOCK
-- ----------------------------
ALTER TABLE "ZHYWUSER"."MH_SIDE_STOCK" ADD CONSTRAINT "SYS_C0017785" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
